### ISSUE TITLE
three test errors 

### ISSUE THREAD

**Issue by mengjianwei12345** [spgroup/pdg-sdg#6]
Hello, I have three test errors when building the project, what is the reason?
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error] br.ufpe.cin.flowdroid.BasicTestSuite
[error] br.ufpe.cin.graph.NewScalaGraphTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 65 s, completed 2022-8-5 11:34:16

**Comment by galilasmb** [comment]
Thank you so much, I will look into to that and work on it.

**Comment by galilasmb** [comment]
All tests passed in new PR. Thanks so much.
